version: '3.6'
services:
  wallet:
    container_name: '${STAGE}-${APP_NAME}-wallet'
    build: ./wallet
    ports:
      - '8888:8888'
    volumes:
      - ${WALLET_DATA}:/opt/application/data
  postgres:
    container_name: '${STAGE}-${APP_NAME}-postgres'
    image: postgres:11.5-alpine
    ports:
      - '5432:5432'
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    restart: on-failure
  hapi:
    container_name: '${STAGE}-${APP_NAME}-hapi'
    build: ./hapi
    ports:
      - '9090:9090'
    volumes:
      - ./hapi:/usr/app
    environment:
      HAPI_EOS_API_ENDPOINT: '${HAPI_EOS_API_ENDPOINT}'
      HAPI_EOS_API_CHAIN_ID: '${HAPI_EOS_API_CHAIN_ID}'
      HAPI_EOS_BASE_ACCOUNT: '${HAPI_EOS_BASE_ACCOUNT}'
      HAPI_EOS_BASE_ACCOUNT_PASSWORD: '${HAPI_EOS_BASE_ACCOUNT_PASSWORD}'
      HAPI_EOS_WALLET_URL: '${HAPI_EOS_WALLET_URL}'
      HAPI_EOS_BP_JSON_ON_CHAIN: '${HAPI_EOS_BP_JSON_ON_CHAIN}'
      HAPI_EOS_BP_JSON_ON_CHAIN_CONTRACT: '${HAPI_EOS_BP_JSON_ON_CHAIN_CONTRACT}'
      HAPI_EOS_BP_JSON_ON_CHAIN_TABLE: '${HAPI_EOS_BP_JSON_ON_CHAIN_TABLE}'
      HAPI_EOS_BP_JSON_ON_CHAIN_SCOPE: '${HAPI_EOS_BP_JSON_ON_CHAIN_SCOPE}'
      HAPI_HASURA_URL: '${HAPI_HASURA_URL}'
      HAPI_HASURA_ADMIN_SECRET: '${HAPI_HASURA_ADMIN_SECRET}'
      HAPI_SERVER_PORT: '${HAPI_SERVER_PORT}'
      HAPI_SERVER_ADDRESS: '${HAPI_SERVER_ADDRESS}'
      HAPI_SYNC_PRODUCERS_INTERVAL: '${HAPI_SYNC_PRODUCERS_INTERVAL}'
      HAPI_SYNC_PRODUCER_INFO_INTERVAL: '${HAPI_SYNC_PRODUCER_INFO_INTERVAL}'
    restart: on-failure
  hasura:
    container_name: '${STAGE}-${APP_NAME}-hasura'
    image: hasura/graphql-engine:v1.2.1.cli-migrations-v2
    ports:
      - '8080:8080'
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: '${HASURA_GRAPHQL_DATABASE_URL}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: '${HASURA_GRAPHQL_ENABLE_CONSOLE}'
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: '${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}'
    restart: on-failure
    depends_on:
      - postgres
  webapp:
    container_name: '${STAGE}-${APP_NAME}-webapp'
    build:
      context: ./webapp
      args:
        react_app_title: '${REACT_APP_TITLE}'
        react_app_default_producer_logo: '${REACT_APP_DEFAULT_PRODUCER_LOGO}'
        react_app_eos_rate_link: '${REACT_APP_EOS_RATE_LINK}'
        react_app_use_rewards: '${REACT_APP_USE_REWARDS}'
        react_app_use_votes: '${REACT_APP_USE_VOTES}'
        react_app_use_block_producer_agreement_contract: '${REACT_APP_USE_BLOCK_PRODUCER_AGREEMENT_CONTRACT}'
        react_app_hasura_url: '${REACT_APP_HASURA_URL}'
        react_app_eos_api_host: '${REACT_APP_EOS_API_HOST}'
        react_app_eos_api_port: '${REACT_APP_EOS_API_PORT}'
        react_app_eos_api_protocol: '${REACT_APP_EOS_API_PROTOCOL}'
        react_app_eos_chain_id: '${REACT_APP_EOS_CHAIN_ID}'
        react_app_eos_default_exchange_rate: '${REACT_APP_EOS_DEFAULT_EXCHANGE_RATE}'
        react_app_eos_default_exchange_rate_api: '${REACT_APP_EOS_DEFAULT_EXCHANGE_RATE_API}'
        react_app_eos_use_bp_json_on_chain: '${REACT_APP_EOS_USE_BP_JSON_ON_CHAIN}'
        react_app_eos_bp_json_on_chain_contract: '${REACT_APP_EOS_BP_JSON_ON_CHAIN_CONTRACT}'
        react_app_eos_bp_json_on_chain_table: '${REACT_APP_EOS_BP_JSON_ON_CHAIN_TABLE}'
        react_app_eos_bp_json_on_chain_scope: '${REACT_APP_EOS_BP_JSON_ON_CHAIN_SCOPE}'
    ports:
      - '3000:3000'
    depends_on:
      - hasura
