apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dashboard-hapi
  name: dashboard-hapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-hapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dashboard-hapi
    spec:
      imagePullSecrets:
          - name: regcred
      containers:
      - image: ${DOCKER_REGISTRY}/${IMAGE_NAME_HAPI}:${VERSION}
        imagePullPolicy: "Always"
        name: "dashboard-hapi"
        envFrom:
        - configMapRef:
            name: dashboard-hapi-config
        ports:
        - containerPort: 9090
        volumeMounts:
          - name: googlecreds
            mountPath: /app/google-credentials.json
            subPath: file-from-cfgmap
      volumes:
      - name: googlecreds
        configMap:
          name: hapi-googlecreds
