apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: monitor-postgres
  name: monitor-postgres
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: monitor-postgres
