apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: wallet
  name: wallet
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wallet
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network: "true"
        io.kompose.service: wallet
    spec:
      containers:
      - image: eoscostarica506/wallet
        imagePullPolicy: "Always"
        name: "wallet"
        ports:
        - containerPort: 8888
      restartPolicy: Always
