apiVersion: v1
kind: Service
metadata:
  labels:
    app: dashboard-webapp
  name: dashboard-webapp
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
  selector:
    app: dashboard-webapp
