apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dashboard-webapp
  name: dashboard-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-webapp
  template:
    metadata:
      labels:
        app: dashboard-webapp
    spec:
      imagePullSecrets:
          - name: regcred
      containers:
      - image: ${DOCKER_REGISTRY}/${IMAGE_NAME_WEBAPP}:${VERSION}-${REACT_APP_EOS_API_NETWORK_NAME}
        imagePullPolicy: "Always"
        name: dashboard-webapp
        envFrom:
        - configMapRef:
            name: dashboard-webapp-config
        ports:
        - containerPort: 80
      restartPolicy: Always
