name: Build images from latest dev branch

on:
  push:
    branches:
      - dev

jobs:
  create-dev-image:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@0.0.1

      - name: Log in to docker registry
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login \
            --username ${{ secrets.DOCKER_HUB_USER }} \
            --password-stdin

      - name: Build new images and push
        run: |
          make \
            build-docker-images \
            push-docker-images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          # webapp
          PORT: 80
          REACT_APP_TITLE: EOS Jungle Testnet Network Dashboard
          REACT_APP_TAG: ${{ github.ref }}
          REACT_APP_DEFAULT_PRODUCER_LOGO: https://jungle.eosio.online/jungle.png
          REACT_APP_FOOTER_LINKS: '[{"text":"Website","src":"https://jungletestnet.io/"},{"text":"Block Explorer","src":"https://jungle3.bloks.io"},{"text":"Developer Guidelines","src":"https://guide.eoscostarica.io"},{"text":"GitHub","src":"https://github.com/eoscostarica/eosio-dashboard"}]'
          REACT_APP_EOS_RATE_LINK: https://jungle.eosrate.io:8080
          REACT_APP_USE_REWARDS: true
          REACT_APP_USE_VOTES: true
          REACT_APP_USE_CPU_BENCHMARK: true
          REACT_APP_USE_BLOCK_PRODUCER_AGREEMENT_CONTRACT: true
          REACT_APP_HASURA_URL: https://graphql-jungle.eosio.online/v1/graphql
          REACT_APP_EOS_API_NETWORK_NAME: jungle
          REACT_APP_EOS_API_NETWORK_LABEL: Jungle
          REACT_APP_EOS_API_NETWORK_LOGO: https://jungle.eosio.online/jungle.png
          REACT_APP_EOS_API_HOST: jungle.eosio.cr
          REACT_APP_EOS_API_PORT: 443
          REACT_APP_EOS_API_PROTOCOL: https
          REACT_APP_EOS_CHAIN_ID: 2a02a0053e5a8cf73a56ba0fda11e4d92e0238a4a2aa74fccf46d5a910746840
          REACT_APP_EOS_USE_BP_JSON_ON_CHAIN: false
          REACT_APP_EOS_BP_JSON_ON_CHAIN_CONTRACT: producerjson
          REACT_APP_EOS_BP_JSON_ON_CHAIN_TABLE: producerjson
          REACT_APP_EOS_BP_JSON_ON_CHAIN_SCOPE: producerjson
          REACT_APP_TOKEN_SYMBOL: ${{ secrets.REACT_APP_TOKEN_SYMBOL }}
          REACT_APP_NETWORK_URL: '[{"label":"EOS Mainnet","value":"https://mainnet.eosio.online"},{"label":"LACChain EOSIO","value":"https://lacchain.eosio.online"},{"label":"Jungle Testnet","value":"https://jungle.eosio.online"},{"label":"Proton Testnet","value":"https://proton-testnet.eosio.online"},{"label":"Telos Testnet","value":"https://telos-testnet.eosio.online"}]'
          REACT_APP_DISABLED_MENU_ITEMS: '["/missed-blocks","/block-distribution","/cpu-benchmark"]'
          REACT_APP_BLOCK_EXPLORER_URL: "https://jungle3.bloks.io/transaction/${transaction}"
          REACT_APP_STATE_HISTORY_ENABLED: 'false'
          REACT_APP_GOOGLE_ANALITIC_PAGE_ID: 'G-E6Y0EC9FT8'

      - name: Build kubernetes files
        id: build_kubernetes_files
        run: |
          make \
            build-kubernetes
        env:
          # general
          NAMESPACE: jungle-dashboard
          INGRESS_HOST: jungle.eosio.online
          INGRESS_GRAPHQL_HOST: graphql-jungle.eosio.online
          # webapp
          REACT_APP_EOS_API_NETWORK_NAME: jungle
          # postgres
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_DATA: ${{ secrets.POSTGRES_DATA }}
          # hapi
          HAPI_EOS_API_ENDPOINT: https://jungle3.cryptolions.io
          HAPI_EOS_API_CHAIN_ID: 2a02a0053e5a8cf73a56ba0fda11e4d92e0238a4a2aa74fccf46d5a910746840
          HAPI_EOS_BASE_ACCOUNT: ${{ secrets.HAPI_EOS_BASE_ACCOUNT }}
          HAPI_EOS_BASE_ACCOUNT_PASSWORD: ${{ secrets.HAPI_EOS_BASE_ACCOUNT_PASSWORD }}
          HAPI_EOS_MECHANICS_ACCOUNT: ${{ secrets.HAPI_EOS_MECHANICS_ACCOUNT }}
          HAPI_EOS_MECHANICS_PASSWORD: ${{ secrets.HAPI_EOS_MECHANICS_PASSWORD }}
          HAPI_EOS_WALLET_URL: http://dashboard-wallet:8888
          HAPI_EOS_BP_JSON_ON_CHAIN: false
          HAPI_EOS_BP_JSON_ON_CHAIN_CONTRACT: ''
          HAPI_EOS_BP_JSON_ON_CHAIN_TABLE: ''
          HAPI_EOS_BP_JSON_ON_CHAIN_SCOPE: ''
          HAPI_HASURA_URL: http://dashboard-hasura:8080/v1/graphql
          HAPI_HASURA_ADMIN_SECRET: ${{ secrets.HAPI_HASURA_ADMIN_SECRET }}
          HAPI_SERVER_PORT: 9090
          HAPI_SERVER_ADDRESS: '0.0.0.0'
          HAPI_DATABASE_URL: ${{ secrets.HAPI_DATABASE_URL }}
          HAPI_SYNC_PRODUCERS_INTERVAL: 86400
          HAPI_SYNC_PRODUCER_INFO_INTERVAL: 1
          HAPI_SYNC_PRODUCER_CPU_INTERVAL: 6
          HAPI_SYNC_EXCHANGE_RATE: 86400
          HAPI_SYNC_SCHEDULE_HISTORY_INTERVAL: 86400
          HAPI_EOS_EXCHANGE_RATE_API: https://api.coingecko.com/api/v3/simple/price?ids=eos&vs_currencies=usd
          HAPI_COINGECKO_API_TOKEN_ID: eos
          # hasura
          HASURA_GRAPHQL_ENABLE_CONSOLE: true
          HASURA_GRAPHQL_DATABASE_URL: ${{ secrets.HASURA_GRAPHQL_DATABASE_URL }}
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
          HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ${{ secrets.HASURA_GRAPHQL_UNAUTHORIZED_ROLE }}
          HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura-migrations
          HASURA_GRAPHQL_ACTION_BASE_URL: http://dashboard-hapi:9090

      - name: Setup and deploy kubernetes environment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          NAMESPACE: jungle-dashboard
          K8S_BUILD_DIR: build_k8s
        with:
          args: version && make deploy-kubernetes
